"""Generate a Windows version resource for the SFSC PyInstaller build."""

from __future__ import annotations

import re
from pathlib import Path


def _read_project_version(pyproject_path: Path) -> str:
    try:
        import tomllib
    except ModuleNotFoundError:  # pragma: no cover - Python 3.10 fallback
        tomllib = None

    content = pyproject_path.read_text(encoding="utf-8")
    if tomllib is not None:
        data = tomllib.loads(content)
        version = data.get("project", {}).get("version")
        if version:
            return str(version)

    match = re.search(r'(?m)^version\s*=\s*"([^"]+)"', content)
    if not match:
        raise ValueError(f"Could not find project.version in {pyproject_path}")
    return match.group(1)


def _version_tuple(version: str) -> tuple[int, int, int, int]:
    parts = re.split(r"[.+-]", version)
    numbers: list[int] = []
    for part in parts:
        if part.isdigit():
            numbers.append(int(part))
        else:
            break

    while len(numbers) < 4:
        numbers.append(0)

    return tuple(numbers[:4])


def build_version_info(version: str) -> str:
    file_version = _version_tuple(version)
    file_version_csv = ", ".join(str(part) for part in file_version)
    string_version = ".".join(str(part) for part in file_version)

    return f"""# UTF-8
#
# Generated by build_desktop/make_version_file.py. Do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({file_version_csv}),
    prodvers=({file_version_csv}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', 'Tensor - Construcao Civil Lda'),
          StringStruct('FileDescription', 'SFSC - Steel Fan Support Calc'),
          StringStruct('FileVersion', '{string_version}'),
          StringStruct('InternalName', 'SFSC'),
          StringStruct('OriginalFilename', 'SFSC.exe'),
          StringStruct('ProductName', 'SFSC - Steel Fan Support Calc'),
          StringStruct('ProductVersion', '{version}')
        ]
      )
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def write_version_file(repo_root: Path | str, output_path: Path | str | None = None) -> Path:
    root = Path(repo_root).resolve()
    version = _read_project_version(root / "pyproject.toml")
    output = (
        Path(output_path)
        if output_path is not None
        else root / "build_desktop" / "version_info.txt"
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_version_info(version), encoding="utf-8")
    return output


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    output = write_version_file(repo_root)
    print(output)


if __name__ == "__main__":
    main()
